import type { Complaint, Notification, User, ActivityLog, Comment } from './types';

// ─── Demo Users ──────────────────────────────────────────────────────────────
export const DEMO_STUDENT: User = {
  id: 'usr-001',
  name: 'Ganesh Patil',
  email: 'ganesh.patil.comp@jspm.edu.in',
  role: 'STUDENT',
  department: 'Computer Engineering',
  rollNumber: 'COMP2021089',
  year: 'Third Year',
  division: 'B',
  phone: '+91 98765 43210',
  joinedAt: '2021-08-01',
};

export const DEMO_TEACHER: User = {
  id: 'usr-002',
  name: 'Prof. Anil Kadam',
  email: 'anil.kadam.comp@jspm.org',
  role: 'TEACHER',
  department: 'Computer Engineering',
  designation: 'Assistant Professor',
  phone: '+91 98234 56789',
  joinedAt: '2019-06-15',
};

export const DEMO_ADMIN: User = {
  id: 'usr-003',
  name: 'Dr. Suresh Mane',
  email: 'hod.computer@jspm.edu.in',
  role: 'HEAD',
  department: 'Computer Engineering',
  designation: 'Head of Department',
  phone: '+91 99001 12233',
  joinedAt: '2015-07-01',
};

// ─── Demo Complaints ──────────────────────────────────────────────────────────
export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: 'COMP-101',
    title: 'Broken Classroom Door in Room 405',
    description:
      'The main entrance door of Classroom 405 (Fourth Floor, B-Wing) has a broken hinge and handle, preventing proper closing during lectures. Loud corridor noise interferes with class instruction. Immediate repair or hinge replacement is requested.',
    category: 'Infrastructure',
    subcategory: 'Classrooms',
    priority: 'HIGH',
    status: 'SUBMITTED',
    isAnonymous: false,
    complainantId: 'usr-001',
    complainantName: 'Ganesh Patil',
    complainantRole: 'STUDENT',
    assignedTo: 'Dr. Suresh Mane',
    department: 'Computer Engineering',
    createdAt: '2026-08-28T10:00:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
    resolvedAt: undefined,
    closedAt: undefined,
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-101', complaintId: 'COMP-101', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-001', changedByName: 'Ganesh Patil', notes: 'Complaint submitted', changedAt: '2026-08-28T10:00:00Z' },
    ],
  },
  {
    id: 'COMP-104',
    title: 'Lab 5 Projector VGA Connector Broken',
    description:
      'The projector in Laboratory 5 (Ground Floor, A-Wing) has a broken VGA connector which makes it impossible to display teaching materials during practicals. Multiple batches are being affected daily. Immediate replacement is requested.',
    category: 'Infrastructure',
    subcategory: 'Laboratories',
    priority: 'MEDIUM',
    status: 'UNDER_REVIEW',
    isAnonymous: false,
    complainantId: 'usr-001',
    complainantName: 'Ganesh Patil',
    complainantRole: 'STUDENT',
    assignedTo: 'Prof. Anil Kadam',
    department: 'Computer Engineering',
    createdAt: '2026-08-18T09:30:00Z',
    updatedAt: '2026-08-19T11:00:00Z',
    resolvedAt: undefined,
    closedAt: undefined,
    comments: [
      {
        id: 'cmt-01',
        authorId: 'usr-002',
        authorName: 'Prof. Anil Kadam',
        authorRole: 'TEACHER',
        content: 'Acknowledged. I have forwarded this to the infrastructure committee. Replacement will be arranged within 3 working days.',
        isAnonymous: false,
        createdAt: '2026-08-19T11:00:00Z',
      },
    ],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-01', complaintId: 'COMP-104', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-001', changedByName: 'Ganesh Patil', notes: 'Complaint submitted', changedAt: '2026-08-18T09:30:00Z' },
      { id: 'hist-02', complaintId: 'COMP-104', oldStatus: 'SUBMITTED', newStatus: 'UNDER_REVIEW', changedBy: 'usr-003', changedByName: 'Dr. Suresh Mane', notes: 'Under review by HOD', changedAt: '2026-08-18T10:00:00Z' },
    ],
  },
  {
    id: 'COMP-098',
    title: 'Discrepancy in Mid-Sem Marks Sheet',
    description:
      'My mid-semester marks in the subject "Data Structures and Algorithms" (DSA) show 12/25 but my answer sheet clearly shows correct answers scoring at least 18/25. I request a re-evaluation of my answer sheet under the supervision of the subject faculty.',
    category: 'Academics',
    subcategory: 'Marks/Results',
    priority: 'HIGH',
    status: 'ASSIGNED',
    isAnonymous: false,
    complainantId: 'usr-001',
    complainantName: 'Ganesh Patil',
    complainantRole: 'STUDENT',
    assignedTo: 'Dr. Suresh Mane',
    department: 'Computer Engineering',
    createdAt: '2026-08-15T14:00:00Z',
    updatedAt: '2026-08-16T09:00:00Z',
    resolvedAt: undefined,
    closedAt: undefined,
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-03', complaintId: 'COMP-098', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-001', changedByName: 'Ganesh Patil', notes: 'Complaint submitted', changedAt: '2026-08-15T14:00:00Z' },
      { id: 'hist-04', complaintId: 'COMP-098', oldStatus: 'SUBMITTED', newStatus: 'ASSIGNED', changedBy: 'usr-003', changedByName: 'Dr. Suresh Mane', notes: 'Assigned to HOD', changedAt: '2026-08-16T09:00:00Z' },
    ],
  },
  {
    id: 'COMP-081',
    title: 'Water Cooler 2nd Floor Filter Replacement',
    description:
      'The water cooler on the second floor near the library has a clogged filter. The water tastes bad and appears discolored. Several students have complained of stomach issues.',
    category: 'Infrastructure',
    subcategory: 'Electricity/Water',
    priority: 'LOW',
    status: 'RESOLVED',
    isAnonymous: false,
    complainantId: 'usr-001',
    complainantName: 'Ganesh Patil',
    complainantRole: 'STUDENT',
    assignedTo: undefined,
    department: 'Computer Engineering',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-12T15:00:00Z',
    resolvedAt: '2026-08-12T15:00:00Z',
    closedAt: undefined,
    comments: [
      {
        id: 'cmt-02',
        authorId: 'usr-003',
        authorName: 'Dr. Suresh Mane',
        authorRole: 'HEAD',
        content: 'Filter has been replaced and water quality tested. Issue resolved. Closing this complaint.',
        isAnonymous: false,
        createdAt: '2026-08-12T15:00:00Z',
      },
    ],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-05', complaintId: 'COMP-081', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-001', changedByName: 'Ganesh Patil', notes: 'Complaint submitted', changedAt: '2026-08-10T10:00:00Z' },
      { id: 'hist-06', complaintId: 'COMP-081', oldStatus: 'SUBMITTED', newStatus: 'RESOLVED', changedBy: 'usr-003', changedByName: 'Dr. Suresh Mane', notes: 'Resolved by HOD', changedAt: '2026-08-12T15:00:00Z' },
    ],
  },
  {
    id: 'COMP-105',
    title: 'Lab 3 Air Conditioning Leakage',
    description:
      'The air conditioning unit in Laboratory 3 (First Floor, B-Wing) is leaking water onto the floor causing a slip hazard and damaging electrical equipment nearby. Urgent attention is required.',
    category: 'Infrastructure',
    subcategory: 'Laboratories',
    priority: 'MEDIUM',
    status: 'SUBMITTED',
    isAnonymous: false,
    complainantId: 'usr-002',
    complainantName: 'Prof. Anil Kadam',
    complainantRole: 'TEACHER',
    assignedTo: undefined,
    department: 'Computer Engineering',
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: '2026-08-19T08:00:00Z',
    resolvedAt: undefined,
    closedAt: undefined,
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-07', complaintId: 'COMP-105', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-002', changedByName: 'Prof. Anil Kadam', notes: 'Complaint submitted', changedAt: '2026-08-19T08:00:00Z' },
    ],
  },
  {
    id: 'COMP-095',
    title: 'Damaged Classroom Whiteboard in Room 302',
    description:
      'The whiteboard in Room 302 is severely damaged with a broken surface. Writing is not visible properly from more than half the classroom. Students are having difficulty following lectures.',
    category: 'Infrastructure',
    subcategory: 'Classrooms',
    priority: 'LOW',
    status: 'RESOLVED',
    isAnonymous: false,
    complainantId: 'usr-002',
    complainantName: 'Prof. Anil Kadam',
    complainantRole: 'TEACHER',
    assignedTo: undefined,
    department: 'Computer Engineering',
    createdAt: '2026-08-11T09:30:00Z',
    updatedAt: '2026-08-13T14:00:00Z',
    resolvedAt: '2026-08-13T14:00:00Z',
    closedAt: undefined,
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-08', complaintId: 'COMP-095', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-002', changedByName: 'Prof. Anil Kadam', notes: 'Complaint submitted', changedAt: '2026-08-11T09:30:00Z' },
      { id: 'hist-09', complaintId: 'COMP-095', oldStatus: 'SUBMITTED', newStatus: 'RESOLVED', changedBy: 'usr-003', changedByName: 'Dr. Suresh Mane', notes: 'Whiteboard replaced', changedAt: '2026-08-13T14:00:00Z' },
    ],
  },
  {
    id: 'COMP-072',
    title: 'Unfair Evaluation Allegation',
    description:
      'Confidential complaint regarding alleged bias in the evaluation process for internal assessment. Identity withheld for safety. Evidence can be provided upon request to super admin.',
    category: 'Academics',
    subcategory: 'Marks/Results',
    priority: 'URGENT',
    status: 'ESCALATED',
    isAnonymous: true,
    complainantId: 'usr-anon',
    complainantName: 'Anonymous Teacher',
    complainantRole: 'TEACHER',
    assignedTo: 'Director Office',
    department: 'Computer Engineering',
    createdAt: '2026-08-05T16:00:00Z',
    updatedAt: '2026-08-08T10:00:00Z',
    resolvedAt: undefined,
    closedAt: undefined,
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-10', complaintId: 'COMP-072', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-anon', changedByName: 'Anonymous Teacher', notes: 'Complaint submitted', changedAt: '2026-08-05T16:00:00Z' },
      { id: 'hist-11', complaintId: 'COMP-072', oldStatus: 'UNDER_REVIEW', newStatus: 'ESCALATED', changedBy: 'usr-003', changedByName: 'Dr. Suresh Mane', notes: 'Escalated to director', changedAt: '2026-08-08T10:00:00Z' },
    ],
  },
  {
    id: 'COMP-067',
    title: 'Scholarship Portal Access Issue',
    description:
      'Several students from the OBC category are unable to log into the scholarship portal due to a system error. The deadline is approaching and immediate technical support is needed.',
    category: 'Finance & Fees',
    subcategory: 'Scholarship',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    isAnonymous: false,
    complainantId: 'usr-anon2',
    complainantName: 'Anonymous Student',
    complainantRole: 'STUDENT',
    assignedTo: 'Prof. Anil Kadam',
    department: 'Computer Engineering',
    createdAt: '2026-08-07T11:00:00Z',
    updatedAt: '2026-08-09T14:00:00Z',
    resolvedAt: undefined,
    closedAt: undefined,
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-12', complaintId: 'COMP-067', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-anon2', changedByName: 'Anonymous Student', notes: 'Complaint submitted', changedAt: '2026-08-07T11:00:00Z' },
      { id: 'hist-13', complaintId: 'COMP-067', oldStatus: 'UNDER_REVIEW', newStatus: 'IN_PROGRESS', changedBy: 'usr-002', changedByName: 'Prof. Anil Kadam', notes: 'Working on portal issue', changedAt: '2026-08-09T14:00:00Z' },
    ],
  },
  {
    id: 'COMP-060',
    title: 'Canteen Food Quality Complaint',
    description:
      'Food quality in the main canteen has deteriorated significantly. Multiple students have complained about stale food being served during lunch hours between 1PM-2PM.',
    category: 'Hostel & Canteen',
    subcategory: 'Food Quality',
    priority: 'MEDIUM',
    status: 'CLOSED',
    isAnonymous: false,
    complainantId: 'usr-004',
    complainantName: 'Priya Sharma',
    complainantRole: 'STUDENT',
    assignedTo: undefined,
    department: 'Information Technology',
    createdAt: '2026-07-28T13:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
    resolvedAt: '2026-08-01T09:00:00Z',
    closedAt: '2026-08-01T09:00:00Z',
    comments: [],
    attachments: [],
    assignments: [],
    statusHistory: [
      { id: 'hist-14', complaintId: 'COMP-060', oldStatus: undefined, newStatus: 'SUBMITTED', changedBy: 'usr-004', changedByName: 'Priya Sharma', notes: 'Complaint submitted', changedAt: '2026-07-28T13:00:00Z' },
      { id: 'hist-15', complaintId: 'COMP-060', oldStatus: 'SUBMITTED', newStatus: 'RESOLVED', changedBy: 'usr-003', changedByName: 'Dr. Suresh Mane', notes: 'Canteen inspected', changedAt: '2026-08-01T09:00:00Z' },
      { id: 'hist-16', complaintId: 'COMP-060', oldStatus: 'RESOLVED', newStatus: 'CLOSED', changedBy: 'usr-004', changedByName: 'Priya Sharma', notes: 'Complainant confirmed closure', changedAt: '2026-08-01T09:00:00Z' },
    ],
  },
];

// ─── Student Notifications ────────────────────────────────────────────────────
export const STUDENT_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-01',
    title: 'Complaint Assigned',
    message: 'Your complaint COMP-098 has been assigned to Dr. Suresh Mane for review.',
    type: 'info',
    read: false,
    createdAt: '2026-08-16T09:00:00Z',
    complaintId: 'COMP-098',
  },
  {
    id: 'notif-02',
    title: 'Response Received',
    message: 'Prof. Anil Kadam has responded to your complaint COMP-104.',
    type: 'success',
    read: false,
    createdAt: '2026-08-19T11:05:00Z',
    complaintId: 'COMP-104',
  },
  {
    id: 'notif-03',
    title: 'Complaint Resolved',
    message: 'Your complaint COMP-081 has been resolved and closed. Please confirm.',
    type: 'success',
    read: true,
    createdAt: '2026-08-12T15:05:00Z',
    complaintId: 'COMP-081',
  },
  {
    id: 'notif-04',
    title: 'System Notice',
    message: 'The grievance portal will undergo scheduled maintenance on 25 Aug 2026 from 11PM-1AM.',
    type: 'warning',
    read: true,
    createdAt: '2026-08-18T10:00:00Z',
  },
];

// ─── Admin Notifications ──────────────────────────────────────────────────────
export const ADMIN_NOTIFICATIONS: Notification[] = [
  {
    id: 'anotif-01',
    title: 'New Escalated Complaint',
    message: 'Complaint COMP-072 has been escalated to your desk for urgent review.',
    type: 'error',
    read: false,
    createdAt: '2026-08-08T10:00:00Z',
    complaintId: 'COMP-072',
  },
  {
    id: 'anotif-02',
    title: 'SLA Breach Warning',
    message: 'Complaint COMP-067 is approaching SLA deadline. Resolution required within 24 hours.',
    type: 'warning',
    read: false,
    createdAt: '2026-08-14T08:00:00Z',
    complaintId: 'COMP-067',
  },
  {
    id: 'anotif-03',
    title: 'New Complaint Submitted',
    message: 'Prof. Anil Kadam submitted a new complaint COMP-105 on infrastructure.',
    type: 'info',
    read: true,
    createdAt: '2026-08-19T08:05:00Z',
    complaintId: 'COMP-105',
  },
];

// ─── Activity Logs ────────────────────────────────────────────────────────────
export const ACTIVITY_LOGS: ActivityLog[] = [
  { id: 'log-01', action: 'Status changed to UNDER_REVIEW', complaintId: 'COMP-104', complaintTitle: 'Lab 5 Projector VGA Connector Broken', performedBy: 'Dr. Suresh Mane', timestamp: '2026-08-18T10:00:00Z' },
  { id: 'log-02', action: 'Assigned to Prof. Anil Kadam', complaintId: 'COMP-104', complaintTitle: 'Lab 5 Projector VGA Connector Broken', performedBy: 'Dr. Suresh Mane', timestamp: '2026-08-18T10:05:00Z' },
  { id: 'log-03', action: 'Status changed to ASSIGNED', complaintId: 'COMP-098', complaintTitle: 'Discrepancy in Mid-Sem Marks Sheet', performedBy: 'Dr. Suresh Mane', timestamp: '2026-08-16T09:00:00Z' },
  { id: 'log-04', action: 'Status changed to RESOLVED', complaintId: 'COMP-081', complaintTitle: 'Water Cooler 2nd Floor Filter Replacement', performedBy: 'Dr. Suresh Mane', timestamp: '2026-08-12T15:00:00Z' },
  { id: 'log-05', action: 'Status changed to ESCALATED', complaintId: 'COMP-072', complaintTitle: 'Unfair Evaluation Allegation', performedBy: 'Dr. Suresh Mane', timestamp: '2026-08-08T10:00:00Z' },
];

// ─── Admin Category Stats ─────────────────────────────────────────────────────
export const CATEGORY_STATS = [
  { name: 'Academics', count: 18, pct: 40, color: 'bg-blue-500' },
  { name: 'Infrastructure', count: 15, pct: 33, color: 'bg-emerald-500' },
  { name: 'Finance & Fees', count: 7, pct: 15, color: 'bg-amber-500' },
  { name: 'Anti-Ragging', count: 5, pct: 12, color: 'bg-rose-500' },
];

export const PRIORITY_STATS = [
  { name: 'Urgent', count: 5, color: 'text-rose-400 bg-rose-500/10 border-rose-500/20' },
  { name: 'High', count: 12, color: 'text-amber-400 bg-amber-500/10 border-amber-500/20' },
  { name: 'Medium', count: 20, color: 'text-blue-400 bg-blue-500/10 border-blue-500/20' },
  { name: 'Low', count: 8, color: 'text-slate-400 bg-slate-500/10 border-slate-500/20' },
];
